apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Ensure this matches the app label in your backend deployment YAML
  ports:
    - protocol: TCP
      port: 5000  # The port the backend service will expose
      targetPort: 5000  # The port your backend container is listening on
  type: ClusterIP  # This makes the service only accessible within the cluster
