apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend  # Ensure this matches the app label in your frontend deployment YAML
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose
      targetPort: 80  # The port your frontend container is listening on
  type: NodePort  # This makes the service accessible externally using Minikube
