apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: db  # Ensure this matches the app label in your postgres deployment YAML
  ports:
    - protocol: TCP
      port: 5432  # Default PostgreSQL port
      targetPort: 5432
  type: ClusterIP  # This makes the service accessible only within the cluster
