apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encode your sensitive values (e.g., JWT secret, DB password)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 for "password"
  JWT_SECRET_KEY: YWJjZGVmZ2hpamtpbG5nCw==  # base64 for your secret key
